# Generated by Django 5.1 on 2024-10-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="name_unaccented",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name_unaccented",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
